apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared platform services managed by platform team
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: ingress-system
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: kyverno.io
      kind: ClusterPolicy
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
