apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-api-secrets
spec:
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /gitops/sample-api/stage
        property: API_KEY
