apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: sample-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /gitops/sample-api/dev
        property: API_KEY
