apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-api
spec:
  minReplicas: 2
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: sample-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
