apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: no-latest-image-tag
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - Rollout
      validate:
        message: "using :latest image tag is not allowed"
        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                all:
                  - key: "{{ contains(element.image, ':latest') }}"
                    operator: Equals
                    value: true
