apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces/base
  - ../../ingress/overlays/shared
  - ../../external-secrets/overlays/shared
  - ../../monitoring/overlays/shared
  - ../../argo-rollouts/overlays/shared
  - ../../policies/kyverno/overlays/shared
