apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sample-api-analysis
spec:
  args:
    - name: namespace
      value: sample-api-dev
    - name: successRateMin
      value: "97"
    - name: p95MaxSeconds
      value: "0.9"
    - name: readyMin
      value: "0.95"
