apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: prod
  source:
    repoURL: https://github.com/your-org/argocd-gitops.git
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-api-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
