apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - monitoring.yaml
  - ingress-system.yaml
  - external-secrets.yaml
  - argo-rollouts.yaml
  - kyverno.yaml
  - sample-api-dev.yaml
  - sample-api-stage.yaml
  - sample-api-prod.yaml
